export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESFULL = 'REGISTER_USER_SUCCESFULL';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const SESSION_USER_SUCCESFULL = 'SESSION_USER_SUCCESFULL';
export const SESSION_USER_FAILURE = 'SESSION_USER_FAILURE';

export const LOGOUT = 'LOGOUT';
export const DELETE_PROFILE = 'DELETE_PROFILE';

export const GET_ADS_REQUEST = 'GET_ADS_REQUEST';
export const GET_ADS_SUCCESFULL = 'GET_ADS_SUCCESFULL';
export const GET_ADS_FAILURE = 'GET_ADS_FAILURE';

export const GET_AD_REQUEST = 'GET_AD_REQUEST';
export const GET_AD_SUCCESFULL = 'GET_AD_SUCCESFULL';
export const GET_AD_FAILURE = 'GET_AD_FAILURE';

export const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST';
export const GET_TAGS_SUCCESFULL = 'GET_TAGS_SUCCESFULL';
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE';