export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESFULL = 'REGISTER_USER_SUCCESFULL';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const GET_ADS_REQUEST = 'GET_ADS_REQUEST';
export const GET_ADS_SUCCESFULL = 'GET_ADS_SUCCESFULL';
export const GET_ADS_FAILURE = 'GET_ADS_FAILURE';