export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESFULL = 'REGISTER_USER_SUCCESFULL';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const SESSION_USER_SUCCESFULL = 'SESSION_USER_SUCCESFULL';
export const SESSION_USER_FAILURE = 'SESSION_USER_FAILURE';

export const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS';
export const RESET_PASS_FAILURE = 'RESET_PASS_FAILURE';

export const LOGOUT = 'LOGOUT';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const DELETE_PROFILE_FAIL = 'DELETE_PROFILE_FAIL';

export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

export const GET_ADS_REQUEST = 'GET_ADS_REQUEST';
export const GET_ADS_SUCCESFULL = 'GET_ADS_SUCCESFULL';
export const GET_ADS_FAILURE = 'GET_ADS_FAILURE';

export const GET_AD_REQUEST = 'GET_AD_REQUEST';
export const GET_AD_SUCCESFULL = 'GET_AD_SUCCESFULL';
export const GET_AD_FAILURE = 'GET_AD_FAILURE';

export const NEW_AD_SUCCESFULL = 'NEW_AD_SUCCESFULL';
export const NEW_AD_FAILURE = 'NEW_AD_FAILURE';

export const DELETE_AD_SUCCESFULL = 'DELETE_AD_SUCCESFULL';
export const DELETE_AD_FAILURE = 'DELETE_AD_FAILURE';

export const UPDATE_AD_SUCCESFULL = 'UPDATE_AD_SUCCESFULL';
export const UPDATE_AD_FAILURE = 'UPDATE_AD_FAILURE';

export const REVERT_ADS = 'REVERT_ADS';

export const ADD_FAVORITE_SUCCESFULL = 'ADD_FAVORITE_SUCCESFULL';
export const ADD_FAVORITE_FAILURE = 'ADD_FAVORITE_FAILURE';

export const GET_FAVORITES_SUCCESFULL = 'ADD_FAVORITE_SUCCESFULL';
export const GET_FAVORITES_FAILURE = 'ADD_FAVORITE_FAILURE';

export const DELETE_FAVORITE_SUCCESFULL = 'DELETE_FAVORITE_SUCCESFULL';
    export const DELETE_FAVORITE_FAILURE = 'DELETE_FAVORITE_FAILURE';

export const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST';
export const GET_TAGS_SUCCESFULL = 'GET_TAGS_SUCCESFULL';
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE';